### PR TITLE
Meet Swift Testing

### PR DESCRIPTION
**Pull request by dagronf**
Added 'Meet Swift Testing'

### CODE REVIEW

**Comment by dagronf** [comment]
Closing this as https://github.com/WWDCNotes/WWDCNotes/pull/21 does a better job. Plus it was pushed a submitted a few minutes earlier 😊

**Comment by petermolnar-dev** [comment]
Thanks for your kind works @dagronf! I am not sure if you checked out the [discussion](https://github.com/WWDCNotes/WWDCNotes/discussions/1) about the claiming of the topics: . 
I am not sure it is quite clear in the [guide](https://wwdcnotes.github.io/WWDCNotes/documentation/wwdcnotes/contributing/) (for me it wasn't for the first read), but the target is to claim a topic right after the WWDC to prevent double work. 
However, I would really like to thank you for your work, and if you find anything to fix or improve in https://github.com/WWDCNotes/WWDCNotes/pull/21, feel free to add!

**Comment by Jeehut** [comment]
@dagronf Feel free to adjust the document by Peter with your own points. There's no reason to keep a note restricted to one person. I'm sure you have points currently missing.

@petermolnar-dev Feel free to edit the `Contributing.md` file to make it more clear if you found anything to be unclear. It's all in the same repo.

**Comment by dagronf** [comment]
@petermolnar-dev @Jeehut Absolutely my fault mate. I should have read the contributing doco beforehand.

**Pull request closed without merging**
